export const QUERY_IS_REMOTELY = "isRemotely"; 
export const QUERY_PARENT_CATEGORY_ID = "parentCategoryId";
export const QUERY_CHILDREN_CATEGORY_ID = "childrenCategoryId";
export const QUERY_IS_SHORT_TIME_JOBS = "isShortTimeJobs";
export const QUERY_IS_TODAY_JOBS = "isTodayJobs";
export const QUERY_JOB_TYPE = "jobType";
export const QUERY_DISTRICTS = "districtIds"; // query districts
export const QUERY_PROVINCES = "provinceId"; // query provinces
export const QUERY_LIST_CHILDREN_CATEGORY_ID = "listChildrenCategoryId"; // query list children category id